# Generated by Django 5.1.6 on 2025-02-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(choices=[('USD', 'US Dollar')], default='USD', max_length=3)),
                ('target_currency', models.CharField(choices=[('Bs', 'Bolívares'), ('EUR', 'Euro')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('Bs', 'Bolívares'), ('EUR', 'Euro')], default='USD', max_length=3),
        ),
    ]
