# Generated by Django 5.1.6 on 2025-02-26 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
