# Generated by Django 5.1.6 on 2025-02-23 14:18

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_product_created_by_product_minimum_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=inventory.models.generate_unique_sku, max_length=50, unique=True),
        ),
    ]
