# Generated by Django 5.1.6 on 2025-02-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(unique=True)),
                ('total_orders', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('best_selling_products', models.JSONField(blank=True, default=list, null=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
