# Generated by Django 5.1.6 on 2025-03-05 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_invoice_invoice_number'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='table.table'),
        ),
    ]
