# Generated by Django 5.1.6 on 2025-02-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_salesreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='best_selling_products',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='total_orders',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='total_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
