# Generated by Django 5.1.6 on 2025-02-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_salesreport_best_selling_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='month',
            field=models.CharField(unique=True),
        ),
    ]
