# Generated by Django 5.1.6 on 2025-02-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_price_at_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesReport',
        ),
    ]
